# Generated by Django 6.0.2 on 2026-02-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_updated', 'Task Updated'), ('reminder', 'Reminder Triggered'), ('deadline', 'Deadline Reached'), ('chat_message', 'Chat Message Received'), ('task_comment', 'New Comment on Task')], max_length=30),
        ),
    ]
